# Generated by Django 4.0.2 on 2022-02-04 22:58

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('market_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=50)),
            ],
        ),
    ]
