# Generated by Django 4.0.2 on 2022-02-04 23:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='market_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=50),
        ),
    ]
